### ISSUE TITLE
Apparently the "number" is not issued anymore

### ISSUE THREAD

**Issue by kmindi** [latextemplates/uni-stuttgart-computer-science-cover#12] opened 2017-03-16 19:53 UTC
The official template has not been updated http://www.informatik.uni-stuttgart.de/fachbereich/gremien/pruefungsausschuesse/Formulare/StADA_Titelseite.pdf

I have no official confirmation about this.

**Comment by koppor** [comment] 2017-03-16 20:43
See https://github.com/latextemplates/scientific-thesis-template/pull/52 for a solution.

**Comment by koppor** [comment] 2017-03-16 20:43
Duplicate of https://github.com/latextemplates/scientific-thesis-template/issues/51

**Closed** 2017-03-16 20:54 UTC
